baseurl: https://csiro-mlai.github.io/HybridPredictionReview/
languageCode: en-us
publishDir: docs/
title: Hybrid prediction notes
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
  page: /:slug/
menu:
  main:
    - name: Learning PDEs
      url: /page/learning_pdes/
    - name: Groundwater emulation
      url: /page/groundwater_emulation/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Notes towards emulating everything
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
    - python
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
