---
title: Hydrology meeting notes
author: Dan MacKinlay
date: '2021-05-05'
publishdate: '2021-04-19'
slug: hydrology-meeting-notes
categories: []
tags: []
nocite:
- '@*'
bibliography: refs.bib
---

# Present

* Dan MacKinlay
* Tao Cui
* Dan Pagendam
* …

# Since last time

* data concatenation bug

  * bugfix submitted to Zongyi Li
  * His code now performs better (!), and the results beat the published work 
  
* [our code updated to pytorch 1.8 ](https://github.com/csiro-mlai/GroundwaterEmulation/tree/master) (faster *and* simpler)
* challenge: there is still bad prediction on the synthetic test data. 

# Discussions

* challenge:  New experiments support the idea that the problem with bad performance on synthetic test data is not the code bug, but that out-of-distribution predictions are bad. If the input data is unphysical, the output is meaningless. (Predictions from the validation set are pretty good, just no the synthetic examples)
* learning new tools is annoying
* learnable discretisation models [@BarSinaiLearning2019]


# Next steps

* integrate modflow PDE data
* integrate Navier-stoke PDE data
* start lit review doc ([meeting style guide](https://www.elsevier.com/wps/find/journaldescription.cws_home/743096?generatepdf=true))

# References

::: {#refs}
:::

