---
title: Hydrology meeting notes
author: Dan MacKinlay
date: '2021-06-16'
slug: hydrology-meeting-notes
categories: []
tags: []
nocite:
- '@*'
bibliography: refs.bib
---

# Present


# Since last time

* MARS2021 😅
* [groundwater modeling review doc commenced](https://www.overleaf.com/3226512942vxpbqtsrggtn)
* further development in Fourier Neural Operator

  * ported reference PDE solver to pytorch 1.8 so that it can be run with the emulator
  
# Discussions

* FNO matters arising.

  * Induces multiple UQ problems
  
    * emulator OOD uncertainty
    * classic model uncertainty
  
  * Conditionalising on latent parameters (WIP)
  
    * Needs conditional simulations (code in development)
    * Need conditional NN (code not yet started)
    * State is “too long” — do we really want to learn 10 steps of history for each forward step? It is manageable but messy.
    * Can we teach the simulator to learn hidden state (velocity etc) _instead_ of past time steps?

      * model-based NN might be a solution here — see @RevachKalmannet2021 in the  ICASSP2021 proceedings

* Alasdair Tran (Working with Alex Matthews and Lexing Xie at ANU) is working on exactly this model (2d fluid flow in time) and encountering sdimilar problems. May be worth code sharing.

# Next steps

* Conditionalising model
* data ingestion
* OOD error
* mixture density?

# References

::: {#refs}
:::

